apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-10-23T08:09:30Z"
  labels:
    app: api
  name: api
  namespace: default
  resourceVersion: "10400"
  selfLink: /api/v1/namespaces/default/services/api
  uid: 27db17cf-ca3f-439f-a7e7-a18db8001556
spec:
  clusterIP: 10.0.95.41
  ports:
  - name: api-traffic
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
